### ISSUE TITLE
Remove copyrighted metadata in files

### ISSUE THREAD

**Issue by oclero** [Bertram25/ChildrenOfSolarus#26]
Some files have copyrighted metadata, because just renaming them didn't change metadata. I don't have the full list for the moment, but these files are issued:

 - [ ] **neptune_appears.it:**
  -  Title is "Release of Ganon" (open in VLC to see it)

You can keep on adding files to this issue if you find some.

**Comment by christopho** [comment]
Actually this music is still the zelda one, it was only renamed. So it is normal that the metadata says Ganon. Sorry I told you to open an issue :P
