### ISSUE TITLE
Bug: Sample Quest - Old hero default after death  

### ISSUE THREAD

**Issue by Zefk** [Bertram25/ChildrenOfSolarus#30]
**Bug Report:**
I was playing with the sample quest and made the hero die after setting too much bombs. Diarandor's hero sprite is no longer used after death. The old sample quest default sprite is used instead and that sprite goes invisible during sword usage.

**Comment by Renkineko** [comment]
Already reported in solarus christopho/solarus#952, it seems a problem with the engine :)

**Comment by christopho** [comment]
Children of Solarus is not the place to report bugs of the sample quest.
Also, the bug was already reported (and it is a bug of the sample quest, not of the engine)

**Comment by Zefk** [comment]
Logically, I thought this would be the place to report bugs for the sample quest. Sorry about that. I will make sure to report them to the engine.

**Comment by christopho** [comment]
No problem. Children of Solarus is a remake project of Zelda Mystery of Solarus DX without Zelda assets, and the sample quest is just a collection of sample maps, sprites, etc. It is true that they both use the same assets.
